[{"exception": "ERROR", "inner": [{"provider": {"package": "org.postgresql.core.v3", "class": "QueryExecutorImpl", "method": "execute", "filename": "QueryExecutorImpl", "line": "255"}, "caller": {"package": "org.postgresql.jdbc2", "class": "AbstractJdbc2Statement", "method": "execute", "filename": "AbstractJdbc2Statement", "line": "559"}}, {"provider": {"package": "org.postgresql.jdbc2", "class": "AbstractJdbc2Statement", "method": "executeUpdate", "filename": "AbstractJdbc2Statement", "line": "363"}, "caller": {"package": "com.mchange.v2.c3p0.impl", "class": "NewProxyPreparedStatement", "method": "executeUpdate", "filename": "NewProxyPreparedStatement", "line": "105"}}], "outer_pre": [], "outer_suf": [], "all": []}]