[{"exception": "Exception", "inner": [{"provider": {"package": "org.eclipse.persistence.testing.framework", "class": "TestExecutor", "method": "runTest", "filename": "TestExecutor", "line": "668"}, "caller": {"package": "org.eclipse.persistence.testing.framework.ui", "class": "SynchronizedTestExecutor", "method": "run", "filename": "SynchronizedTestExecutor", "line": "61"}}], "outer_pre": [], "outer_suf": [{"provider": {"package": "org.eclipse.persistence.testing.framework", "class": "TestExecutor", "method": "runTest", "filename": "TestExecutor", "line": "668"}, "caller": {"package": "org.eclipse.persistence.testing.framework.ui", "class": "SynchronizedTestExecutor", "method": "run", "filename": "SynchronizedTestExecutor", "line": "61"}}], "all": [{"provider": {"package": "org.eclipse.persistence.testing.framework", "class": "TestExecutor", "method": "runTest", "filename": "TestExecutor", "line": "668"}, "caller": {"package": "org.eclipse.persistence.testing.framework.ui", "class": "SynchronizedTestExecutor", "method": "run", "filename": "SynchronizedTestExecutor", "line": "61"}}]}, {"exception": "junit.framework.AssertionFailedError", "inner": [{"provider": {"package": "junit.framework", "class": "Assert", "method": "fail", "filename": "Assert", "line": "47"}, "caller": {"package": "org.eclipse.persistence.testing.tests.unitofwork", "class": "CommitUnitOfWorkForcingSQLExceptionTest", "method": "test", "filename": "CommitUnitOfWorkForcingSQLExceptionTest", "line": "74"}}, {"provider": {"package": "org.eclipse.persistence.testing.tests.unitofwork", "class": "CommitUnitOfWorkForcingSQLExceptionTest", "method": "test", "filename": "CommitUnitOfWorkForcingSQLExceptionTest", "line": "74"}, "caller": {"package": "org.eclipse.persistence.testing.framework", "class": "TestCase", "method": "executeTest", "filename": "TestCase", "line": "541"}}], "outer_pre": [{"provider": {"package": "junit.framework", "class": "Assert", "method": "fail", "filename": "Assert", "line": "47"}, "caller": {"package": "org.eclipse.persistence.testing.tests.unitofwork", "class": "CommitUnitOfWorkForcingSQLExceptionTest", "method": "test", "filename": "CommitUnitOfWorkForcingSQLExceptionTest", "line": "74"}}, {"provider": {"package": "org.eclipse.persistence.testing.tests.unitofwork", "class": "CommitUnitOfWorkForcingSQLExceptionTest", "method": "test", "filename": "CommitUnitOfWorkForcingSQLExceptionTest", "line": "74"}, "caller": {"package": "org.eclipse.persistence.testing.framework", "class": "TestCase", "method": "executeTest", "filename": "TestCase", "line": "541"}}], "outer_suf": [], "all": [{"provider": {"package": "junit.framework", "class": "Assert", "method": "fail", "filename": "Assert", "line": "47"}, "caller": {"package": "org.eclipse.persistence.testing.tests.unitofwork", "class": "CommitUnitOfWorkForcingSQLExceptionTest", "method": "test", "filename": "CommitUnitOfWorkForcingSQLExceptionTest", "line": "74"}}, {"provider": {"package": "org.eclipse.persistence.testing.tests.unitofwork", "class": "CommitUnitOfWorkForcingSQLExceptionTest", "method": "test", "filename": "CommitUnitOfWorkForcingSQLExceptionTest", "line": "74"}, "caller": {"package": "org.eclipse.persistence.testing.framework", "class": "TestCase", "method": "executeTest", "filename": "TestCase", "line": "541"}}]}]