[{"exception": "Exception", "inner": [], "outer_pre": [], "outer_suf": [], "all": []}, {"exception": "Exception", "inner": [], "outer_pre": [], "outer_suf": [], "all": []}, {"exception": "junit.framework.AssertionFailedError", "inner": [{"provider": {"package": "org.eclipse.persistence.testing.tests.unitofwork", "class": "CommitUnitOfWorkForcingSQLExceptionTest", "method": "test", "filename": "CommitUnitOfWorkForcingSQLExceptionTest", "line": "74"}, "caller": {"package": "org.eclipse.persistence.testing.framework", "class": "TestCase", "method": "executeTest", "filename": "TestCase", "line": "543"}}], "outer_pre": [{"provider": {"package": "org.eclipse.persistence.testing.tests.unitofwork", "class": "CommitUnitOfWorkForcingSQLExceptionTest", "method": "test", "filename": "CommitUnitOfWorkForcingSQLExceptionTest", "line": "74"}, "caller": {"package": "org.eclipse.persistence.testing.framework", "class": "TestCase", "method": "executeTest", "filename": "TestCase", "line": "543"}}], "outer_suf": [], "all": [{"provider": {"package": "org.eclipse.persistence.testing.tests.unitofwork", "class": "CommitUnitOfWorkForcingSQLExceptionTest", "method": "test", "filename": "CommitUnitOfWorkForcingSQLExceptionTest", "line": "74"}, "caller": {"package": "org.eclipse.persistence.testing.framework", "class": "TestCase", "method": "executeTest", "filename": "TestCase", "line": "543"}}]}]