{"stack_id": 507637, "component": "General", "importance": "P3 normal", "reported_time": "2016-11-16 17:48", "modified_time": "2017-03-09 14:48", "stack_arr": [{"exception": "exception", "calls": [{"package": "org.eclipse.cft.server.core.internal", "class": "CloudErrorUtil", "method": "toCoreException", "filename": "CloudErrorUtil", "line": "408"}, {"package": "org.eclipse.cft.server.core.internal", "class": "CloudErrorUtil", "method": "toCoreException", "filename": "CloudErrorUtil", "line": "394"}, {"package": "org.eclipse.cft.server.core.internal.client", "class": "ApplicationOperation", "method": "doApplicationOperation", "filename": "ApplicationOperation", "line": "104"}, {"package": "org.eclipse.cft.server.core.internal.client", "class": "AbstractPublishApplicationOperation", "method": "run", "filename": "AbstractPublishApplicationOperation", "line": "90"}, {"package": "org.eclipse.cft.server.ui.internal.actions", "class": "PushModuleCommand$1", "method": "run", "filename": "PushModuleCommand", "line": "79"}, {"package": "org.eclipse.core.internal.jobs", "class": "Worker", "method": "run", "filename": "Worker", "line": "55"}]}], "duplicated_stack_id": []}